stages:
  - build

variables:
  CONTAINER_BUILD_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  CONTAINER_BUILD_IMAGE_LATEST: $CI_REGISTRY_IMAGE:latest

image: node:latest

docker:build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
    - docker pull $CONTAINER_BUILD_IMAGE_LATEST || true
    - docker build -t $CONTAINER_BUILD_IMAGE --cache-from $CONTAINER_BUILD_IMAGE_LATEST .
    - docker push $CONTAINER_BUILD_IMAGE
    - |
        if [[ $CI_COMMIT_REF_NAME = "master" ]]
        then
          docker tag $CONTAINER_BUILD_IMAGE $CONTAINER_BUILD_IMAGE_LATEST
          docker push $CONTAINER_BUILD_IMAGE_LATEST
        fi
  only:
    - branches
  retry: 2

pages:
  stage: build
  image: node:latest
  script:
    - npm install
    - CONFIG_PATH=$(pwd)/config-example.json nodejs build.js
    - cd pages
    - npm install
    - ./node_modules/.bin/ng build --prod --base-href /elite-dangerous/elitetracker/
    - mv dist/elitetracker ../public
    - cp ../public/index.html ../public/404.html
  artifacts:
    paths:
      - public
  only:
    - master
