{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "elitetracker.serviceAccountName" . }}
  labels:
{{ include "elitetracker.labels" . | indent 4 }}
{{- end -}}
