{{- if .Values.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "elitetracker.fullname" . }}
  annotations:
  {{- with .Values.persistence.annotations  }}
{{ toYaml . | indent 4 }}
  {{- end }}
  labels:
{{ include "elitetracker.labels" . | indent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  {{- end }}
{{- end -}}
