const commoditiesMap = {
	'Aluminium': 'Aluminium',
	'Beryllium': 'Beryllium',
	'Bismuth': 'Bismuth',
	'Cobalt': 'Cobalt',
	'Copper': 'Copper',
	'Gallium': 'Gallium',
	'Gold': 'Gold',
	'H178': 'Hafnium178',
	'Indium': 'Indium',
	'Lanthanum': 'Lanthanum',
	'Lithium': 'Lithium',
	'Osmium': 'Osmium',
	'Palladium': 'Palladium',
	'Platinum': 'Platinum',
	'Praseodymium': 'Praseodymium',
	'Samarium': 'Samarium',
	'Silver': 'Silver',
	'Tantalum': 'Tantalum',
	'Thallium': 'Thallium',
	'Thorium': 'Thorium',
	'Titanium': 'Titanium',
	'Uranium': 'Uranium',
	'Alexandrite': 'Alexandrite',
	'Bauxite': 'Bauxite',
	'Benitoite': 'Benitoite',
	'Bertrandite': 'Bertrandite',
	'Bromellite': 'Bromellite',
	'Coltan': 'Coltan',
	'Cryolite': 'Cryolite',
	'Gallite': 'Gallite',
	'Goslarite': 'Goslarite',
	'Grandidierite': 'Grandidierite',
	'Indite': 'Indite',
	'Jadeite': 'Jadeite',
	'Lepidolite': 'Lepidolite',
	'LH': 'LithiumHydroxide',
	'LTD': 'LowTemperatureDiamond',
	'MC': 'MethaneClathrate',
	'MMC': 'MethanolMonohydrateCrystals',
	'Moissanite': 'Moissanite',
	'Monazite': 'Monazite',
	'Musgravite': 'Musgravite',
	'VOpal': 'Opal',
	'Painite': 'Painite',
	'Pyrophyllite': 'Pyrophyllite',
	'Rhodplumsite': 'Rhodplumsite',
	'Rutile': 'Rutile',
	'Serendibite': 'Serendibite',
	'Taaffeite': 'Taaffeite',
	'Uraninite': 'Uraninite',
	'Tritium': 'Tritium',
};
const commoditiesTranslation = {
	'Aluminium': 'Aluminium',
	'Beryllium': 'Beryllium',
	'Bismuth': 'Bismuth',
	'Cobalt': 'Cobalt',
	'Copper': 'Copper',
	'Gallium': 'Gallium',
	'Gold': 'Gold',
	'Hafnium178': 'Hafnium 178',
	'Indium': 'Indium',
	'Lanthanum': 'Lanthanum',
	'Lithium': 'Lithium',
	'Osmium': 'Osmium',
	'Palladium': 'Palladium',
	'Platinum': 'Platinum',
	'Praseodymium': 'Praseodymium',
	'Samarium': 'Samarium',
	'Silver': 'Silver',
	'Tantalum': 'Tantalum',
	'Thallium': 'Thallium',
	'Thorium': 'Thorium',
	'Titanium': 'Titanium',
	'Uranium': 'Uranium',
	'Alexandrite': 'Alexandrite',
	'Bauxite': 'Bauxite',
	'Benitoite': 'Benitoite',
	'Bertrandite': 'Bertrandite',
	'Bromellite': 'Bromellite',
	'Coltan': 'Coltan',
	'Cryolite': 'Cryolite',
	'Gallite': 'Gallite',
	'Goslarite': 'Goslarite',
	'Grandidierite': 'Grandidierite',
	'Indite': 'Indite',
	'Jadeite': 'Jadeite',
	'Lepidolite': 'Lepidolite',
	'LithiumHydroxide': 'Lithium Hydroxide',
	'LowTemperatureDiamond': 'Low Temperature Diamonds',
	'MethaneClathrate': 'Methane Clathrate',
	'MethanolMonohydrateCrystals': 'Methanol Monohydrate Crystals',
	'Moissanite': 'Moissanite',
	'Monazite': 'Monazite',
	'Musgravite': 'Musgravite',
	'Opal': 'Void Opals',
	'Painite': 'Painite',
	'Pyrophyllite': 'Pyrophyllite',
	'Rhodplumsite': 'Rhodplumsite',
	'Rutile': 'Rutile',
	'Serendibite': 'Serendibite',
	'Taaffeite': 'Taaffeite',
	'Uraninite': 'Uraninite',
	'Tritium': 'Tritium',
};

module.exports = {
	commoditiesMap: commoditiesMap,
	commoditiesTranslation: commoditiesTranslation,
	allowedCommodities: Object.keys(commoditiesMap),
};

